<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>disable</Nullable>
        <LangVersion>latest</LangVersion>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <Version>3.2.0</Version>
        <IncludeSymbols>true</IncludeSymbols>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\NetX\NetX.csproj" />

    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="NetX.AutoServiceGenerator.Definitions" Version="4.0.1" />
    </ItemGroup>

</Project>
